Cleanup and set max workers to 4

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -29,7 +29,7 @@ jobs:
       robolectric.logging.enabled: true
 
     steps:
-      - name: set up JDK
+      - name: Set Up JDK
         uses: actions/setup-java@v3
         with:
           distribution: 'zulu'
@@ -43,12 +43,20 @@ jobs:
         uses: actions/checkout@v2
 
       # Issuelink: https://github.com/nektos/act/issues/1172#issuecomment-1699598124
-      - name: Set up Android SDK
+      - name: Set Up Android SDK
         if: ${{ env.ACT }} # Only run on local act setups, as GitHub Actions provides the Android SDK on Ubuntu
         uses: android-actions/setup-android@v2
 
       - name: Start Artemis Server
         run: docker compose -f docker/e2e-tests.yml up artemis-app-setup
 
-      - name: Build
+      - name: Run Tests
         run: ./gradlew test -Dskip.debugVariants=true -Dskip.flavor.unrestricted=true -Dskip.flavor.beta=true
+
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: End-To-End Test Results
+          path: test-outputs/**/*.xml
+          reporter: java-junit
