run unit tests on self hosted runner 2.

diff --git a/.github/workflows/e2e-test.yml b/.github/workflows/e2e-test.yml
--- a/.github/workflows/e2e-test.yml
+++ b/.github/workflows/e2e-test.yml
@@ -8,46 +8,35 @@ on:
   workflow_dispatch:
 
 jobs:
-  end-to-end:
-    runs-on: [self-hosted, ase-large-android-sdk-34, disabled]
+  end-to-end-tests:
+    name: End To End Tests
+    runs-on:
+      labels: self-hosted
+      group: ase-large-android-sdk-34
     timeout-minutes: 60
 
     steps:
       - uses: actions/checkout@v4
 
-      - name: Gather tag parameter values
-        id: calc_tag
-        run: echo "image_tag=$(./scripts/calc_docker_image_tag.sh)" >> $GITHUB_OUTPUT
+      - name: Gradle Wrapper Verification
+        uses: gradle/wrapper-validation-action@v1
 
-      - name: Log in to the Container registry
-        uses: docker/login-action@v2
+      - name: Launch docker containers
+        run: docker compose -f docker/e2e-tests.yml up artemis-app
+
+      - name: JDK setup
+        uses: actions/setup-java@v3
         with:
-          registry: ${{ secrets.REGISTRY_HOST }}
-          username: ${{ secrets.REGISTRY_USERNAME }}
-          password: ${{ secrets.REGISTRY_PASSWORD }}
+          distribution: 'zulu'
+          java-version: 17
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
-
-      - name: Pull android base image
-        run: docker pull $(${{ secrets.REGISTRY_HOST }}/artemis_android_build_image:${{ steps.calc_tag.outputs.image_tag }})
-
-      - name: Build and publish new android base image
-        uses: docker/build-push-action@v5
-        if: failure()
-        with:
-          file: Dockerfile
-          push: true
-          target: builder
-          tags: ${{ secrets.REGISTRY_HOST }}/artemis_android_build_image:${{ steps.calc_tag.outputs.image_tag }}
-
-      - name: Run end to end tests.
-        run: docker compose -f docker/e2e-tests.yml up artemis-android-e2e --abort-on-container-exit --force-recreate
+      - name: run tests
+        run: ./gradlew test --max-workers=4 -Dskip.unit-tests=true -Dskip.e2e=false -Dskip.debugVariants=true -Dskip.flavor.unrestricted=true -Dskip.flavor.beta=true
 
       - name: Test Report
         uses: dorny/test-reporter@v1
-        if: success() || failure()
+        if: success() || failure()    # run this step even if previous step failed
         with:
-          name: End To End Test Results
+          name: Android End To End Test Results
           path: test-outputs/**/*.xml
           reporter: java-junit
