Adding back sanity cleanup for port 3306 (see second to last commit)

diff --git a/.github/workflows/e2e-test.yml b/.github/workflows/e2e-test.yml
--- a/.github/workflows/e2e-test.yml
+++ b/.github/workflows/e2e-test.yml
@@ -35,6 +35,15 @@ jobs:
         if: success() || failure()
         continue-on-error: true
 
+        # Sanity cleanup 2
+      - name: Print what is running on port 3306
+        run: sudo lsof -i:3306 || true
+        continue-on-error: true
+
+      - name: Stop anything still running on port 3306
+        run: sudo kill -9 $(sudo lsof -t -i:3306) || true
+        continue-on-error: true
+
       - name: Launch docker containers
         run: docker compose -f docker/e2e-tests.yml up -d artemis-app-setup
         if: success() || failure()
